### ISSUE TITLE
WORKSPACE and BUILD templates

### ISSUE THREAD

**Issue by nfisher** [nfisher/mvn2bzl#2]
```gherkin
Given a target workspace
When the BUILD and WORKSPACE files are generated
Then they should be rendered from a resource template.
```

## Tasks
- [x] repositories.bzl template and view model.
- [x] WORKSPACE template and view model.
- [x] BUILD template and view model.
