### ISSUE TITLE
Create module nodes

### ISSUE THREAD

**Issue by nfisher** [nfisher/mvn2bzl#4]
```gherkin
Given the `metrics/pom.xml`:
  | groupId    | com.instana    |
  | artifactId | metrics        |
  | version    | 1.0.0-SNAPSHOT |  
When it is processed
Then a module node should be added to the workspace graph.
```

### Tasks

- [ ] subscribe to directory walker queue for `pom.xml` files.
- [ ] read `pom.xml` files using the model reader.
- [ ] add module node with required fields to the workspace graph.

### Required Fields

- path - path to the related `pom.xml` file..
- groupId - maven group ID for this module.
- artifactId - maven artifact ID for this module.
- version - maven version for this module.
