### ISSUE TITLE
Create class and package nodes from source

### ISSUE THREAD

**Issue by nfisher** [nfisher/mvn2bzl#5]
```gherkin
Given a java file exists in a sub-module 
When it's filename is emitted from the walker
Then it should add a unique package node to the workspace graph
And it should add the parsed class nodes.
```

### Tasks

- [ ] subscribe to directory walker queue for `*.java` files.
- [ ] parse source and extract relevant class and package names.
- [ ] add package node with required fields to the workspace graph.

### References

- https://javaparser.org/
