### ISSUE TITLE
Infer package node from path

### ISSUE THREAD

**Issue by nfisher** [nfisher/mvn2bzl#7]
```gherkin
Given a java file exists in a sub-module 
When it's filename is emitted from the walker
Then it should add a unique package node to the workspace graph based on its path.
```

### Tasks

- [ ] subscribe to directory walker queue for `*.java` files.
- [ ] infer the package based on maven standard directory structure.
- [ ] add package node with required fields to the workspace graph.
